security:
    providers:
        db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username
        # in_memory:
        #     memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login$, allow_if: 'not has_role("ROLE_USER")' }
        - { path: ^/signup$, allow_if: 'not has_role("ROLE_USER")' }
        - { path: ^/product, role: ROLE_USER}

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
