# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.file_manager:
        class: AppBundle\Services\FileManager

    app.product_picture_upload_listener:
        class: AppBundle\EventListener\Product\PictureUploadListener
        arguments: ["@app.file_manager", "%app.products_pictures_dir%"]
        tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
